windows: skip TestDecompressStreamBzip2, TestDecompressStreamZstd
These tests fail on Windows. We need to investigate what's the actual
failure. Initially, it seemed due to path conversion and/or use of short
paths ("C:\Users\RUNNER~1\");

    === RUN   TestDecompressStreamBzip2
        archive_test.go:112: Failed to create archive file (exit status 1):
            command: C:\Program Files\Git\usr\bin\sh.exe -c touch /c/Users/RUNNER~1/AppData/Local/Temp/TestDecompressStreamBzip24229910048/001/archive && bzip2 -f /c/Users/RUNNER~1/AppData/Local/Temp/TestDecompressStreamBzip24229910048/001/archive
            output: bzip2.exe: Can't open input file /c/Users/RUNNER~1/AppData/Local/Temp/TestDecompressStreamBzip24229910048/001/archive: No such file or directory.
    --- FAIL: TestDecompressStreamBzip2 (0.14s)
    === RUN   TestDecompressStreamZstd
        archive_test.go:112: Failed to create archive file (exit status 1):
            command: C:\Program Files\Git\usr\bin\sh.exe -c touch /c/Users/RUNNER~1/AppData/Local/Temp/TestDecompressStreamZstd1127536628/001/archive && zstd -f /c/Users/RUNNER~1/AppData/Local/Temp/TestDecompressStreamZstd1127536628/001/archive
            output: zstd: can't stat /c/Users/RUNNER~1/AppData/Local/Temp/TestDecompressStreamZstd1127536628/001/archive : No such file or directory -- ignored
    --- FAIL: TestDecompressStreamZstd (0.09s)

But even expanding those paths to long-paths, and creating the directory
as part of the test continued to fail;

    === RUN   TestDecompressStreamBzip2
        archive_test.go:112: ORIG TEMPDIR IS: C:\Users\RUNNER~1\AppData\Local\Temp\TestDecompressStreamBzip2111433806\001
        archive_test.go:120: LONG TEMPDIR IS: C:\Users\runneradmin\AppData\Local\Temp\TestDecompressStreamBzip2111433806\001
        archive_test.go:121: LONG UNIXDIR IS: /c/Users/runneradmin/AppData/Local/Temp/TestDecompressStreamBzip2111433806/001
        archive_test.go:127: Failed to create archive file (exit status 1):
            command: C:\Program Files\Git\usr\bin\sh.exe -c mkdir -p /c/Users/runneradmin/AppData/Local/Temp/TestDecompressStreamBzip2111433806/001 && touch /c/Users/runneradmin/AppData/Local/Temp/TestDecompressStreamBzip2111433806/001/archive && bzip2 -f /c/Users/runneradmin/AppData/Local/Temp/TestDecompressStreamBzip2111433806/001/archive
            output: bzip2.exe: Can't open input file /c/Users/runneradmin/AppData/Local/Temp/TestDecompressStreamBzip2111433806/001/archive: No such file or directory.
    --- FAIL: TestDecompressStreamBzip2 (0.07s)

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>