skip TestCreateTarFileSymlinkPreservesLinkname (go1.27 regression)
go1.27 contains a breaking change, causing this test to fail;

```
=== RUN   TestCreateTarFileSymlinkPreservesLinkname/relative_posix_target
    archive_test.go:646: assertion failed: ../usr/local/bin/tool (tc.linkname string) != ..\usr\local\bin\tool (target string)
=== RUN   TestCreateTarFileSymlinkPreservesLinkname/absolute_posix_target
    archive_test.go:646: assertion failed: /usr/local/bin/tool (tc.linkname string) != \usr\local\bin\tool (target string)
--- FAIL: TestCreateTarFileSymlinkPreservesLinkname (0.01s)
    --- FAIL: TestCreateTarFileSymlinkPreservesLinkname/relative_posix_target (0.01s)
    --- FAIL: TestCreateTarFileSymlinkPreservesLinkname/absolute_posix_target (0.00s)
```

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>