TestImpliedDirectoryPermissions: require root
    === RUN   TestImpliedDirectoryPermissions
        archive_test.go:1211: assertion failed: error is not nil: chown /tmp/TestImpliedDirectoryPermissions2455386337/001/deeply/nested/and: operation not permitted
    --- FAIL: TestImpliedDirectoryPermissions (0.00s)

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>